name: CI

# Specify which GitHub events will trigger a CI build
on: push

# Define a single job
jobs:
  build:
    # Specify an OS for the runner
    runs-on: ubuntu-latest
      # Define steps
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Setup Python 3.9
          uses: actions/setup-python@v2
          with:
            python version: 3.9

        - name: Install python dependencies
          run: |
            python3 -m pip install --upgrade pip
            pip3 install -r requirements.txt
            pip3 install -e .

        - name: Test with Pytest
          run: |
            pytest tests/test_models.py