name: CI

# Specify which GitHub events will trigger a CI build
on: push

# Define a single job
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8, 3.9]

    # Specify OS of runner
    runs-on: ${{ matrix.os  }}
      # Define steps
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Setup Python version
          uses: actions/setup-python@v2
          with:
            python version: ${{  matrix.python-version  }}

        - name: Install python dependencies
          run: |
            python3 -m pip install --upgrade pip
            pip3 install -r requirements.txt
            pip3 install -e .

        - name: Test with Pytest
          run: |
            pytest tests/test_models.py